# -*- coding: utf-8 -*-
"""labscript

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W7rpelYR5S8EHXIsIcqInKqYdlqGcEpq
"""

print("Various Courses and credits of this semester:- Devops:3, communication skills:3, HPC:5, UGR:1,capstone:1")